stellar_deployment_guide.md

Create a README.md for Contracts in StarShop in the StarShop:
In this Documentation I made a step-by-step instructions and simplified setup process of deploying Smart Contracts using Stellar for new developers
The content of this documentation covers  guides:
Prerequisites: Necessary tools and dependencies.
Environment Setup:
Configuring Stellar Smart Contracts.
- Specific steps to install related tools or plugins.
Wallet Configuration:
- Instructions to connect and configure the wallet.
Compilation and Deployment:
- Detailed explanation for compiling and deploying Smart Contracts.
Testing and Execution:
- A practical, verified example of a deployed Smart Contract.
Troubleshooting:
Tips and solutions for common errors during the setup process.

created stellar_deployment_guide.md file

---

conduct-code.md

Deleted unnecesary file

---

Cargo.toml
GUIDE_CONTRIBUTING.md

add GUIDE_CONTRIBUTING.md

---

Cargo.lock
Cargo.toml

---
---
fix dependencies in Cargo.toml
---
---
---
---

fix dependencies in Cargo.toml

---

Cargo.lock
StarShopContracts/implement-nft-contract/Cargo.toml
StarShopContracts/implement-nft-contract/src/distribution.rs
StarShopContracts/implement-nft-contract/src/lib.rs
StarShopContracts/implement-nft-contract/src/metadata.rs
StarShopContracts/implement-nft-contract/src/minting.rs

---
---
- Added lib.rs
- Added minting.rs
- Added distribution.rs
- Added metadata.rs
---
---
---
---

[Contract] 📂 Implement NFT Contract

---

StarShopContracts/implement-payment-contract/src/dispute.rs
StarShopContracts/implement-payment-contract/src/lib.rs
StarShopContracts/implement-payment-contract/src/refund.rs
StarShopContracts/implement-payment-contract/src/transaction.rs

Ft payment contract

---

StarShopContracts/implement-payment-contract/src/dispute.rs
StarShopContracts/implement-payment-contract/src/lib.rs
StarShopContracts/implement-payment-contract/src/refund.rs
StarShopContracts/implement-payment-contract/src/transaction.rs

fix contract implement contract

---

Cargo.toml
StarShopContracts/product-follow-contract/src/alerts.rs
StarShopContracts/product-follow-contract/src/datatype.rs
StarShopContracts/product-follow-contract/src/follow.rs
StarShopContracts/product-follow-contract/src/interface.rs
StarShopContracts/product-follow-contract/src/lib.rs
StarShopContracts/product-follow-contract/src/notification.rs

---
---
📝 Changes Description
This pull request implements a comprehensive Product Follow System for StarShop, enabling users to track products and receive notifications about price changes, restocks, and special offers. The implementation includes:
Follow Management System
- Product following mechanism with user authentication
- Configurable follow limits with expiration tracking
- Category-based follow preferences
---
Alert System
- Price change detection with customizable thresholds
- Restock notification handling
- Special offer alert processing
---
Notification System
- Priority-based notification delivery
- Efficient storage management with automatic cleanup
---
⏰ Time Spent Breakdown
Total: 4 days
System Design & …

Feature/issue #10 product follow system

---

StarShopContracts/product-follow-contract/src/alerts.rs
StarShopContracts/product-follow-contract/src/datatype.rs
StarShopContracts/product-follow-contract/src/follow.rs
StarShopContracts/product-follow-contract/src/interface.rs
StarShopContracts/product-follow-contract/src/lib.rs
StarShopContracts/product-follow-contract/src/notification.rs

fix contract product follow

---

.github/gitbook-docs.md

- [ x] Closes #33 
---
- [x ] Documentation (updates to README, docs, or comments)
---
Initial documentation covering project overview, setup guides, 
architecture details, and contribution guidelines for frontend, 
backend, and smart contracts. 
The documentation is organized into five main sections:
Overview of StarShop's mission and team.
Quick setup guides and core concepts of the StarShop ecosystem.
Complete documentation for the Next.js frontend application, including setup, architecture, and integration guides.
Comprehensive guide for the Express.js backend, covering setup, architecture, and API documentation.
Detailed documentation for Stellar-based smart contracts, including architecture, contract types, and development …

docu: add comprehensive project documentation structure

---

StarShopContracts/implement-nft-contract/README.md

---
---
- Added a **detailed README** documenting the NFT contract's functionality, deployment, and usage.
- Implemented **unit tests** for:
- `mint_nft`
- `transfer_nft`
- `burn_nft`
- `update_metadata`
- `get_nft_data`
- `get_nft_history`
- Verified **deployment and interaction** on Stellar Testnet.
- Ensured **proper access control** for admin and owner-restricted functions.
- Optimized **storage usage and gas efficiency**.
---
---
---

docs: add readme for implement NFT contract

---

StarShopContracts/product-voting-contract/README.md

---
---
Added a detailed README file for the Product Voting Contract to explain the functionality and provide usage examples. This update aims to improve the understanding of the contract's purpose, its functions, and how to interact with it.
---
---
---

docs: add readme for product-voting-contract

---

StarShopContracts/product-voting-contract/src/lib.rs
StarShopContracts/product-voting-contract/src/limits.rs
StarShopContracts/product-voting-contract/src/test.rs
StarShopContracts/product-voting-contract/src/vote.rs
StarShopContracts/product-voting-contract/test_snapshots/test/tests/test_account_too_new.1.json
StarShopContracts/product-voting-contract/test_snapshots/test/tests/test_create_product.1.json
StarShopContracts/product-voting-contract/test_snapshots/test/tests/test_daily_vote_limit.1.json
StarShopContracts/product-voting-contract/test_snapshots/test/tests/test_duplicate_product_creation.1.json
StarShopContracts/product-voting-contract/test_snapshots/test/tests/test_reversal_window_expired.1.json

---
---
- Replaced `unwrap()` with match and `unwrap_or_else` in `src/limits.rs` to handle missing user votes gracefully.
- In `src/vote.rs`, replaced `unwrap()` with match and `unwrap_or` to handle cases where products or votes may not exist.
- Added appropriate error handling for missing products and votes to prevent panics.
- Added tests to verify the functionality of entry recording and management system.
- Included tests for duplicate entry prevention, entry limit enforcement, and eligibility rules.
- Added checks for participant eligibility, entry restrictions, and qualification rules.
- Ensured edge cases for entry validation are handled properly.
---
---
2 days
---
---
Thank you for contributing to StarShop, we are glad that you have chosen us as your project of choice and we hope …

feat: Add Test cases for entry management, product creation, and voting functionality

---

StarShopContracts/product-follow-contract/README.md

Added comprehensive documentation for the Product Follow System Contract including:
- Overview and key features
- Setup and installation instructions
- Usage examples and core functions
- Configuration and security details
- Testing and error handling documentation
- Research and planning: 30 minutes
- Writing documentation: 1 hour
- Review and refinements: 30 minutes
The documentation follows the project's style guide and includes all necessary information for developers to understand and use the Product Follow System Contract.

[Doc] Add comprehensive README for Product Follow System Contract

---

StarShopContracts/implement-nft-contract/src/test.rs
StarShopContracts/product-follow-contract/src/follow.rs
StarShopContracts/product-voting-contract/src/limits.rs

Test: Metadata Attachment

---

StarShopContracts/product-voting-contract/src/test.rs

---
---
[Test] Result Verification System #17

test: add test for result verification system

---

StarShopContracts/product-follow-contract/src/alerts.rs
StarShopContracts/product-follow-contract/src/datatype.rs
StarShopContracts/product-follow-contract/src/follow.rs
StarShopContracts/product-follow-contract/src/lib.rs
StarShopContracts/product-follow-contract/src/test.rs
StarShopContracts/product-follow-contract/test_snapshots/test/test_add_follower.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_alert_rate_limiting.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_condition_combinations.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_panic_follow_limit_exceeded.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_panic_follower_not_auth.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_panic_user_already_following.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_price_change_alert.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_restock_alert.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_special_offer_alert.1.json
StarShopContracts/product-follow-contract/test_snapshots/test/test_unfollow.1.json

---
---
- **File**: `src/alerts.rs`
- **Changes**:
- Improved the logic for checking if a user is following a product by iterating through the follow list.
- Fixed the notification history key to clone the user address properly.
- **Impact**:
- Ensures accurate tracking of users following a product.
- Prevents potential issues with notification history storage.
- **File**: `src/datatype.rs`
- **Changes**:
- Added a new `DataKeys` variant `ProductFollowers` to store the list of followers for each product.
- **Impact**:
- Enables efficient tracking of followers for individual products.
- **File**: `src/follow.rs`
- **Changes**:
- Refactored the follow system to use `DataKeys` for storage keys.
- Improved the logic for adding and …

Feat: Add test case for alert system

---

StarShopContracts/product-follow-contract/src/test.rs

- [ x] Added tests (if necessary)
- [ x] Run tests
- [x ] Run formatting
- [ x] Evidence attached
- [x ] Commented the code
---
- [x ] Enhancement (non-breaking change which adds functionality)
---
Added test to verify the functionality of the notification delivery system
---
---
2 days
---
---

Addede code for testing notifications delivery

---

StarShopContracts/implement-nft-contract/src/test.rs

feat: test implement nft contract

---

README.md

chore: edited broken links

---

StarShopContracts/crowdfunding-collective/src/lib.rs
StarShopContracts/crowdfunding-collective/src/test.rs
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_claim_reward_no_contributions_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_claim_reward_no_eligible_tier_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_claim_reward_product_not_completed_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_claim_reward_successful.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_contribute_after_deadline_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_contribute_exceeds_goal_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_contribute_successful_and_fund_product.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_contribute_to_funded_product_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_contribute_zero_amount_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_create_product_past_deadline.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_create_product_successful.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_create_product_zero_funding_goal.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_distribute_funds_milestones_not_completed_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_distribute_funds_not_funded_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_distribute_funds_successful.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_get_product_not_found_panics.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_getters_for_non_existent_product.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_initialization.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_initialization_and_admin_set.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_initialize_unauthorized_attempt.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_refund_contributors_before_deadline_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_refund_contributors_product_funded_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_refund_contributors_successful.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_update_milestone_already_completed_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_update_milestone_product_not_funded_fails.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_update_milestone_successful.1.json
StarShopContracts/crowdfunding-collective/test_snapshots/test/test_update_milestone_unauthorized_user_fails.1.json

---
---
- Added comprehensive tests for the Crowdfunding Collective contract covering:
- Contribution flow: funding within deadlines, amount limits, role enforcement, and real-time fund tracking.
- Reward distribution: correct tier-based rewards, non-contributor exclusion, and product registration after success.
- Milestone and progress tracking: creator updates, milestone events, and validation that progress updates don’t alter funds or rewards.
- Refund process: handling funding period expirations, full refunds to contributors, and prevention of invalid refund attempts.
- Security & limits: enforcement of maximum cap per user, identity verification, and secure, consistent contribution recording.
- Clearly described expected …

Feat:  Add Tests For Crowdfunding Flow, Rewards, and Refund Validation
